### ISSUE TITLE
Transfer to The Collective?

### ISSUE THREAD

**Issue by hvelarde** [collective/qi.portlet.TagClouds#6]
do you mind transfer this package to [The Collective](https://github.com/collective)?

now that you're not working with Plone it should be better maintained there :-)

**Comment by ggozad** [comment]
Absolutely! What's the process around that? Would be happy to do the same with the rest of my plone packages, if you think some of the ones under my account are interesting let me know.

**Comment by hvelarde** [comment]
I think you just have to go to the settings screen and transfer to the collective account.

on the others, I have no idea; if I found another interesting I'll let you know :-)

:beer:

**Comment by ggozad** [comment]
Bah I need admin rights on the collective. Will try to sort it out today and will transfer whatever I think is suitable.

**Comment by ggozad** [comment]
Right so here we are. I transferred it, can't seem to close the ticket though ;)

**Comment by hvelarde** [comment]
thanks!
